server:
  port: 9005
spring:
  application:
    name: driver-location-simulator
gpsSimmulator:
  googleApiKey: AIzaSyDvdz2cb4zfp8NQVFu4kdzXFoIcHG744I4

com:
    fleet:
      location:
        ingest: http://localhost:9006